name: glbr
title: Gelbooru

scheme: https
host: gelbooru.com
path: index.php

thumbs:
  dir: /thumbnails/
  part: /thumbnail_
  format: jpg

images:
  dir: /images/
  part: /

samples:
  dir: /samples/
  part: /sample_
  format: jpg
